blank_issues_enabled: false
contact_links:
 - name: IPFS Cluster Website/Documentation issues
   url: https://github.com/ipfs/ipfs-cluster-website
   about: Report issues with the Docs or anything in the IPFS Cluster website.
 - name: Official Documentation
   url: https://cluster.ipfs.io/documentation
   about: Extensive documentation is available at the IPFS Cluster website.
 - name: IPFS Official Forums
   url: https://discuss.ipfs.io
   about: Please post general questions, support requests, and discussions here.
