// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: types.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pin_PinType int32

const (
	Pin_BadType        Pin_PinType = 0
	Pin_DataType       Pin_PinType = 1
	Pin_MetaType       Pin_PinType = 2
	Pin_ClusterDAGType Pin_PinType = 3
	Pin_ShardType      Pin_PinType = 4
)

// Enum value maps for Pin_PinType.
var (
	Pin_PinType_name = map[int32]string{
		0: "BadType",
		1: "DataType",
		2: "MetaType",
		3: "ClusterDAGType",
		4: "ShardType",
	}
	Pin_PinType_value = map[string]int32{
		"BadType":        0,
		"DataType":       1,
		"MetaType":       2,
		"ClusterDAGType": 3,
		"ShardType":      4,
	}
)

func (x Pin_PinType) Enum() *Pin_PinType {
	p := new(Pin_PinType)
	*p = x
	return p
}

func (x Pin_PinType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Pin_PinType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[0].Descriptor()
}

func (Pin_PinType) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[0]
}

func (x Pin_PinType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Pin_PinType.Descriptor instead.
func (Pin_PinType) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0, 0}
}

type Pin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid         []byte      `protobuf:"bytes,1,opt,name=Cid,proto3" json:"Cid,omitempty"`
	Type        Pin_PinType `protobuf:"varint,2,opt,name=Type,proto3,enum=api.pb.Pin_PinType" json:"Type,omitempty"`
	Allocations [][]byte    `protobuf:"bytes,3,rep,name=Allocations,proto3" json:"Allocations,omitempty"`
	MaxDepth    int32       `protobuf:"zigzag32,4,opt,name=MaxDepth,proto3" json:"MaxDepth,omitempty"`
	Reference   []byte      `protobuf:"bytes,5,opt,name=Reference,proto3" json:"Reference,omitempty"`
	Options     *PinOptions `protobuf:"bytes,6,opt,name=Options,proto3" json:"Options,omitempty"`
	Timestamp   uint64      `protobuf:"varint,7,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *Pin) Reset() {
	*x = Pin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pin) ProtoMessage() {}

func (x *Pin) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pin.ProtoReflect.Descriptor instead.
func (*Pin) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *Pin) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *Pin) GetType() Pin_PinType {
	if x != nil {
		return x.Type
	}
	return Pin_BadType
}

func (x *Pin) GetAllocations() [][]byte {
	if x != nil {
		return x.Allocations
	}
	return nil
}

func (x *Pin) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *Pin) GetReference() []byte {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *Pin) GetOptions() *PinOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Pin) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PinOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplicationFactorMin int32               `protobuf:"zigzag32,1,opt,name=ReplicationFactorMin,proto3" json:"ReplicationFactorMin,omitempty"`
	ReplicationFactorMax int32               `protobuf:"zigzag32,2,opt,name=ReplicationFactorMax,proto3" json:"ReplicationFactorMax,omitempty"`
	Name                 string              `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	ShardSize            uint64              `protobuf:"varint,4,opt,name=ShardSize,proto3" json:"ShardSize,omitempty"`
	EncodingScheme       string              `protobuf:"bytes,5,opt,name=EncodingScheme,proto3" json:"EncodingScheme,omitempty"`
	SymbolSize           uint64              `protobuf:"varint,6,opt,name=SymbolSize,proto3" json:"SymbolSize,omitempty"`
	RepairSymbols        int32               `protobuf:"zigzag32,7,opt,name=RepairSymbols,proto3" json:"RepairSymbols,omitempty"`
	TotalSymbols         int32               `protobuf:"zigzag32,8,opt,name=TotalSymbols,proto3" json:"TotalSymbols,omitempty"`
	Metadata             map[string]string   `protobuf:"bytes,9,rep,name=Metadata,proto3" json:"Metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PinUpdate            []byte              `protobuf:"bytes,10,opt,name=PinUpdate,proto3" json:"PinUpdate,omitempty"`
	ExpireAt             uint64              `protobuf:"varint,11,opt,name=ExpireAt,proto3" json:"ExpireAt,omitempty"`
	Origins              [][]byte            `protobuf:"bytes,12,rep,name=Origins,proto3" json:"Origins,omitempty"`
	SortedMetadata       []*Metadata         `protobuf:"bytes,13,rep,name=SortedMetadata,proto3" json:"SortedMetadata,omitempty"`
}

func (x *PinOptions) Reset() {
	*x = PinOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PinOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinOptions) ProtoMessage() {}

func (x *PinOptions) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinOptions.ProtoReflect.Descriptor instead.
func (*PinOptions) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *PinOptions) GetReplicationFactorMin() int32 {
	if x != nil {
		return x.ReplicationFactorMin
	}
	return 0
}

func (x *PinOptions) GetReplicationFactorMax() int32 {
	if x != nil {
		return x.ReplicationFactorMax
	}
	return 0
}

func (x *PinOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PinOptions) GetShardSize() uint64 {
	if x != nil {
		return x.ShardSize
	}
	return 0
}

func (x *PinOptions) GetEncodingScheme() string {
	if x != nil {
		return x.EncodingScheme
	}
	return ""
}

func (x *PinOptions) GetSymbolSize() uint64 {
	if x != nil {
		return x.SymbolSize
	}
	return 0
}

func (x *PinOptions) GetRepairSymbols() int32 {
	if x != nil {
		return x.RepairSymbols
	}
	return 0
}

func (x *PinOptions) GetTotalSymbols() int32 {
	if x != nil {
		return x.TotalSymbols
	}
	return 0
}

func (x *PinOptions) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PinOptions) GetPinUpdate() []byte {
	if x != nil {
		return x.PinUpdate
	}
	return nil
}

func (x *PinOptions) GetExpireAt() uint64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *PinOptions) GetOrigins() [][]byte {
	if x != nil {
		return x.Origins
	}
	return nil
}

func (x *PinOptions) GetSortedMetadata() []*Metadata {
	if x != nil {
		return x.SortedMetadata
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Metadata) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_types_proto protoreflect.FileDescriptor

var file_types_proto_rawDesc = []byte{
	// Add your raw descriptor data here.
}

var file_types_proto_rawDescOnce sync.Once
var file_types_proto_rawDescData = file_types_proto_rawDesc

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_proto_rawDescData)
	})
	return file_types_proto_rawDescData
}

var file_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_types_proto_goTypes = []interface{}{
	(Pin_PinType)(0),   // 0: api.pb.Pin.PinType
	(*Pin)(nil),        // 1: api.pb.Pin
	(*PinOptions)(nil), // 2: api.pb.PinOptions
	(*Metadata)(nil),   // 3: api.pb.Metadata
}
var file_types_proto_depIdxs = []int32{
	0, // 0: api.pb.Pin.Type:type_name -> api.pb.Pin.PinType
	2, // 1: api.pb.Pin.Options:type_name -> api.pb.PinOptions
	3, // 2: api.pb.PinOptions.SortedMetadata:type_name -> api.pb.Metadata
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PinOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		EnumInfos:         file_types_proto_enumTypes,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_rawDesc = nil
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
